#!/bin/bash
# Regenerates requirements.txt, the pinned lock installed by update.sh, from
# requirements.in. Needs uv (https://docs.astral.sh/uv/). Run after editing
# requirements.in, then test a fresh install on each supported Python version.
#
# The lock is "universal": one file whose environment markers pick the right pins for
# every supported Python version, so update.sh and a plain `pip install -r` need no
# per-version logic. Packages that are compiled locally on Linux (no Linux wheels) are
# listed with a version range instead of an exact pin, so an update reuses what is already
# built instead of recompiling it.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.."

source_built=(pyaudio pygobject pycairo evdev)
args=()
for package in "${source_built[@]}"; do
    args+=(--no-emit-package "$package")
done

lock="$(mktemp)"
trap 'rm -f "$lock"' EXIT
uv pip compile requirements.in --universal --python-version 3.10 \
    --quiet --no-header --no-annotate "${args[@]}" -o "$lock" "$@"

{
    echo '# Generated by tools/lock_requirements.sh from requirements.in - do not edit by hand.'
    echo '# Supported: CPython 3.10-3.14 on Linux. Install: venv/bin/python3 -m pip install -r requirements.txt'
    echo
    grep -v '^#' "$lock" | sed '/^$/d'
    echo
    echo '# Compiled locally (no Linux wheels); ranges keep an existing build. See README.md for'
    echo '# the apt packages they need.'
    echo 'pyaudio==0.2.14'
    echo 'PyGObject>=3.42,<4'
    echo 'evdev>=1.3; sys_platform == "linux"'
} > requirements.txt
echo "Wrote requirements.txt"
